Repository najinl/wellnews, pull requests merged in 2021-11, with the labels that each got.

#10 Styles/feed view
  public/index.html
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Card/Card.css
  src/components/Feed/Feed.css
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/index.css
Labels: enhancement

#16 Feature/sort
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Feed/Feed.tsx
  src/components/Form/Form.tsx
Labels: enhancement

#21 Feature/form info button
  src/components/Form/Form.css
  src/components/Form/Form.tsx
Labels: enhancement

#12 Add router, modify assignSentiment function, fix WAVE errors
  package-lock.json
  package.json
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Card/Card.css
  src/components/Feed/Feed.css
  src/components/Form/Form.tsx
Labels: enhancement

#26 Refactor/architecture
  README.md
  public/index.html
  public/logo192.png
  public/logo512.png
  public/robots.txt
  src/Models.tsx
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Card/Card.tsx
  src/components/Feed/Feed.tsx
  src/components/Form/Form.tsx
  src/index.tsx
Labels: chore

#29 Feature/testing
  cypress.json
  cypress/fixtures/affair-sentiment.json
  cypress/fixtures/manhattan-madam-sentiment.json
  cypress/fixtures/nyt-article-fetch.json
  cypress/integration/Feed_spec.js
  cypress/integration/form_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/App/App.tsx
  src/components/Card/Card.tsx
  src/components/Form/Form.tsx
Labels: chore

#34 Refactor/dandelion text
  src/apiCalls.tsx
  src/components/Feed/Feed.tsx
Labels: enhancement

#35 Feature/article view
  src/Models.tsx
  src/apiCalls.tsx
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Article/Article.css
  src/components/Article/Article.tsx
  src/components/Card/Card.css
  src/components/Card/Card.tsx
  src/components/Feed/Feed.css
  src/components/Feed/Feed.tsx
  src/index.css
Labels: enhancement

#37 Feature/alternating neutral sorting
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Card/Card.tsx
  src/components/Feed/Feed.tsx
Labels: enhancement

#38 Feature/sort by section
  src/Models.tsx
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Card/Card.tsx
  src/components/Feed/Feed.tsx
  src/components/SectionForm/SectionForm.tsx
Labels: enhancement

#51 Cypress/article view
  cypress/integration/Article_spec.js
  src/components/App/App.tsx
  src/components/Article/Article.tsx
  src/components/Card/Card.tsx
  src/components/NoMatch/NoMatch.css
  src/components/NoMatch/NoMatch.tsx
Labels: chore

#52 Feature/skip and retake questionnaire
  package-lock.json
  public/manifest.json
  src/components/Feed/Feed.tsx
  src/components/Form/Form.css
  src/components/Form/Form.tsx
Labels: enhancement

#53 Feature/sentiment range
  cypress/integration/form_spec.js
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/index.css
Labels: enhancement

#58 Feature/history
  src/Models.tsx
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Card/Card.tsx
  src/components/Feed/Feed.css
  src/components/Feed/Feed.tsx
  src/components/Form/Form.tsx
  src/components/History/History.css
  src/components/History/History.tsx
  src/components/NoMatch/NoMatch.tsx
  src/components/TopicCard/TopicCard.tsx
  src/components/TopicFeed/TopicFeed.tsx
Labels: enhancement

#59 Styles/feed rework
  src/apiCalls.tsx
  src/assets/back-arrow-active.svg
  src/assets/back-arrow.svg
  src/assets/list-btn-active.svg
  src/assets/list-btn.svg
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Article/Article.tsx
  src/components/Card/Card.css
  src/components/Card/Card.tsx
  src/components/Feed/Feed.css
  src/components/Feed/Feed.tsx
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/components/Header/Header.css
  src/components/Header/Header.tsx
  src/components/History/History.tsx
  src/components/NoMatch/NoMatch.css
  src/components/SectionForm/SectionForm.css
  src/components/SectionForm/SectionForm.tsx
  src/components/SectionForm/hamburger-menu.svg
  src/components/TopicCard/TopicCard.tsx
  src/components/TopicFeed/TopicFeed.tsx
  src/components/TopicForm/TopicForm.css
  src/components/TopicForm/TopicForm.tsx
  src/index.css
Labels: styling

#60 Resize elements in individual article view
  src/components/Article/Article.css
  src/components/Feed/Feed.css
  src/components/Header/Header.css
Labels: styling

#61 Feature/history page
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Article/Article.tsx
  src/components/Card/Card.tsx
  src/components/Feed/Feed.css
  src/components/Feed/Feed.tsx
  src/components/Form/Form.tsx
  src/components/Header/Header.tsx
  src/components/History/History.tsx
  src/components/TopicCard/TopicCard.tsx
  src/components/TopicFeed/TopicFeed.tsx
  src/components/TopicForm/TopicForm.tsx
Labels: enhancement

#64 Add media queries for topic selection form
  src/components/Feed/Feed.css
  src/components/TopicForm/TopicForm.css
  src/components/TopicForm/TopicForm.tsx
Labels: enhancement

#66 Add token and remove console.log
  src/apiCalls.tsx
  src/components/TopicCard/TopicCard.tsx
Labels: chore

#71 Refactor/consolidate feeds and cards
  package-lock.json
  src/Models.tsx
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Article/Article.css
  src/components/Article/Article.tsx
  src/components/Card/Card.tsx
  src/components/Feed/Feed.tsx
  src/components/History/History.tsx
  src/components/SectionForm/SectionForm.css
  src/components/SectionForm/SectionForm.tsx
  src/components/SectionForm/hamburger-menu.svg
  src/components/SentimentForm/SentimentForm.css
  src/components/SentimentForm/SentimentForm.tsx
  src/components/TopicCard/TopicCard.tsx
  src/components/TopicFeed/TopicFeed.tsx
Labels: chore

#76 Add carousel functionality and abstract to feed cards
  .DS_Store
  public/index.html
  src/apiCalls.tsx
  src/components/App/App.css
  src/components/Card/Card.css
  src/components/Card/Card.tsx
  src/components/Feed/Feed.css
  src/components/Feed/Feed.tsx
  src/components/History/History.tsx
  src/components/SentimentForm/SentimentForm.css
  src/components/TopicForm/TopicForm.tsx
  src/index.css
Labels: enhancement

#77 Feature/save articles
  src/assets/icon-not-saved.png
  src/assets/icon-saved.png
  src/components/App/App.tsx
  src/components/Card/Card.tsx
  src/components/Feed/Feed.css
  src/components/Feed/Feed.tsx
  src/components/Header/Header.css
  src/components/Header/Header.tsx
  src/components/History/History.css
  src/components/History/History.tsx
  src/components/SavedArticles/SavedArticles.tsx
  src/components/TopicForm/TopicForm.css
  src/components/TopicForm/TopicForm.tsx
Labels: enhancement

#82 Refactor/styling
  src/assets/check-in-icon.png
  src/assets/history-btn.svg
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Card/Card.css
  src/components/Card/Card.tsx
  src/components/Feed/Feed.css
  src/components/Feed/Feed.tsx
  src/components/Header/Header.css
  src/components/Header/Header.tsx
  src/components/History/History.tsx
  src/components/NoMatch/NoMatch.css
  src/components/NoMatch/NoMatch.tsx
  src/components/SavedArticles/SavedArticles.tsx
  src/components/SentimentForm/SentimentForm.css
  src/components/TopicForm/TopicForm.css
  src/components/TopicForm/TopicForm.tsx
  src/index.css
Labels: styling

#88 Make final style adjustments
  src/apiCalls.tsx
  src/assets/multi-emoji.png
  src/components/Feed/Feed.css
  src/components/Feed/Feed.tsx
  src/components/Header/Header.css
  src/components/SentimentForm/SentimentForm.css
  src/components/SentimentForm/SentimentForm.tsx
Labels: styling

#89 Fix/routes and clean articles
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Feed/Feed.tsx
  src/components/Header/Header.tsx
  src/components/NoMatch/NoMatch.tsx
  src/components/SentimentForm/SentimentForm.tsx
  src/components/TopicForm/TopicForm.tsx
Labels: bug

#90 Set menu button to open/close on successvie clicks
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Feed/Feed.tsx
  src/components/Header/Header.tsx
  src/components/History/History.tsx
  src/components/SavedArticles/SavedArticles.tsx
  src/components/TopicForm/TopicForm.tsx
Labels: bug
